# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogMakeTemp.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(638, 758)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(638, 758))
        Dialog.setMaximumSize(QtCore.QSize(638, 758))
        self.grpTemp = QtWidgets.QGroupBox(Dialog)
        self.grpTemp.setGeometry(QtCore.QRect(9, 9, 621, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTemp.sizePolicy().hasHeightForWidth())
        self.grpTemp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.grpTemp.setFont(font)
        self.grpTemp.setObjectName("grpTemp")
        self.frame = QtWidgets.QFrame(self.grpTemp)
        self.frame.setGeometry(QtCore.QRect(10, 570, 601, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, -1, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.labModel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labModel.sizePolicy().hasHeightForWidth())
        self.labModel.setSizePolicy(sizePolicy)
        self.labModel.setObjectName("labModel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labModel)
        self.lineEditModel = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditModel.sizePolicy().hasHeightForWidth())
        self.lineEditModel.setSizePolicy(sizePolicy)
        self.lineEditModel.setObjectName("lineEditModel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditModel)
        self.labColor = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labColor.sizePolicy().hasHeightForWidth())
        self.labColor.setSizePolicy(sizePolicy)
        self.labColor.setObjectName("labColor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labColor)
        self.lineEditColor = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditColor.sizePolicy().hasHeightForWidth())
        self.lineEditColor.setSizePolicy(sizePolicy)
        self.lineEditColor.setObjectName("lineEditColor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditColor)
        self.labSize = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSize.sizePolicy().hasHeightForWidth())
        self.labSize.setSizePolicy(sizePolicy)
        self.labSize.setObjectName("labSize")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labSize)
        self.comboBoxSize = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSize.sizePolicy().hasHeightForWidth())
        self.comboBoxSize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxSize.setFont(font)
        self.comboBoxSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxSize.setObjectName("comboBoxSize")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.comboBoxSize.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxSize)
        self.scrollArea = QtWidgets.QScrollArea(self.grpTemp)
        self.scrollArea.setGeometry(QtCore.QRect(10, 22, 601, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labTemp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labTemp.sizePolicy().hasHeightForWidth())
        self.labTemp.setSizePolicy(sizePolicy)
        self.labTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labTemp.setObjectName("labTemp")
        self.verticalLayout_3.addWidget(self.labTemp)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 700, 621, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.grpTemp.setTitle(_translate("Dialog", "模板"))
        self.labModel.setText(_translate("Dialog", "型号"))
        self.labColor.setText(_translate("Dialog", "颜色"))
        self.labSize.setText(_translate("Dialog", "尺码"))
        self.comboBoxSize.setItemText(0, _translate("Dialog", "XS"))
        self.comboBoxSize.setItemText(1, _translate("Dialog", "S"))
        self.comboBoxSize.setItemText(2, _translate("Dialog", "M"))
        self.comboBoxSize.setItemText(3, _translate("Dialog", "L"))
        self.comboBoxSize.setItemText(4, _translate("Dialog", "XL"))
        self.comboBoxSize.setItemText(5, _translate("Dialog", "XXL"))
        self.comboBoxSize.setItemText(6, _translate("Dialog", "XXXL"))
        self.labTemp.setText(_translate("Dialog", "无图片"))


