# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogSetParams.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 697)
        Dialog.setMinimumSize(QtCore.QSize(463, 697))
        Dialog.setMaximumSize(QtCore.QSize(463, 697))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.labExposureTime = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labExposureTime.sizePolicy().hasHeightForWidth())
        self.labExposureTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labExposureTime.setFont(font)
        self.labExposureTime.setTextFormat(QtCore.Qt.AutoText)
        self.labExposureTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labExposureTime.setObjectName("labExposureTime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labExposureTime)
        self.spinBoxExposureTime = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxExposureTime.sizePolicy().hasHeightForWidth())
        self.spinBoxExposureTime.setSizePolicy(sizePolicy)
        self.spinBoxExposureTime.setMaximum(1000000)
        self.spinBoxExposureTime.setObjectName("spinBoxExposureTime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxExposureTime)
        self.labTriggerDelay = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labTriggerDelay.sizePolicy().hasHeightForWidth())
        self.labTriggerDelay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labTriggerDelay.setFont(font)
        self.labTriggerDelay.setTextFormat(QtCore.Qt.AutoText)
        self.labTriggerDelay.setAlignment(QtCore.Qt.AlignCenter)
        self.labTriggerDelay.setObjectName("labTriggerDelay")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labTriggerDelay)
        self.spinBoxTriggerDelay = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxTriggerDelay.sizePolicy().hasHeightForWidth())
        self.spinBoxTriggerDelay.setSizePolicy(sizePolicy)
        self.spinBoxTriggerDelay.setMaximum(1000)
        self.spinBoxTriggerDelay.setObjectName("spinBoxTriggerDelay")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxTriggerDelay)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBoxIntervalTime = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxIntervalTime.sizePolicy().hasHeightForWidth())
        self.spinBoxIntervalTime.setSizePolicy(sizePolicy)
        self.spinBoxIntervalTime.setObjectName("spinBoxIntervalTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxIntervalTime)
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBoxDelay = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxDelay.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxDelay.setSizePolicy(sizePolicy)
        self.doubleSpinBoxDelay.setDecimals(1)
        self.doubleSpinBoxDelay.setSingleStep(0.1)
        self.doubleSpinBoxDelay.setObjectName("doubleSpinBoxDelay")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxDelay)
        self.labMinMatchCount = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labMinMatchCount.sizePolicy().hasHeightForWidth())
        self.labMinMatchCount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labMinMatchCount.setFont(font)
        self.labMinMatchCount.setAlignment(QtCore.Qt.AlignCenter)
        self.labMinMatchCount.setObjectName("labMinMatchCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labMinMatchCount)
        self.spinBoxMinMatchCount = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxMinMatchCount.sizePolicy().hasHeightForWidth())
        self.spinBoxMinMatchCount.setSizePolicy(sizePolicy)
        self.spinBoxMinMatchCount.setObjectName("spinBoxMinMatchCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxMinMatchCount)
        self.labResizeTime = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labResizeTime.sizePolicy().hasHeightForWidth())
        self.labResizeTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labResizeTime.setFont(font)
        self.labResizeTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labResizeTime.setObjectName("labResizeTime")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labResizeTime)
        self.doubleSpinBoxResizeTimes = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxResizeTimes.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxResizeTimes.setSizePolicy(sizePolicy)
        self.doubleSpinBoxResizeTimes.setDecimals(3)
        self.doubleSpinBoxResizeTimes.setMaximum(1.0)
        self.doubleSpinBoxResizeTimes.setSingleStep(0.001)
        self.doubleSpinBoxResizeTimes.setObjectName("doubleSpinBoxResizeTimes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxResizeTimes)
        self.labMaxMatches = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labMaxMatches.sizePolicy().hasHeightForWidth())
        self.labMaxMatches.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labMaxMatches.setFont(font)
        self.labMaxMatches.setAlignment(QtCore.Qt.AlignCenter)
        self.labMaxMatches.setObjectName("labMaxMatches")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labMaxMatches)
        self.spinBoxMaxMatches = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxMaxMatches.sizePolicy().hasHeightForWidth())
        self.spinBoxMaxMatches.setSizePolicy(sizePolicy)
        self.spinBoxMaxMatches.setMaximum(10000)
        self.spinBoxMaxMatches.setObjectName("spinBoxMaxMatches")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxMaxMatches)
        self.labHist1 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labHist1.sizePolicy().hasHeightForWidth())
        self.labHist1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labHist1.setFont(font)
        self.labHist1.setObjectName("labHist1")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labHist1)
        self.doubleSpinBoxHist1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHist1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHist1.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHist1.setMaximum(1.0)
        self.doubleSpinBoxHist1.setSingleStep(0.01)
        self.doubleSpinBoxHist1.setObjectName("doubleSpinBoxHist1")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxHist1)
        self.labHist2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labHist2.sizePolicy().hasHeightForWidth())
        self.labHist2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labHist2.setFont(font)
        self.labHist2.setObjectName("labHist2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labHist2)
        self.doubleSpinBoxHist2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHist2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHist2.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHist2.setMaximum(1.0)
        self.doubleSpinBoxHist2.setSingleStep(0.01)
        self.doubleSpinBoxHist2.setObjectName("doubleSpinBoxHist2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxHist2)
        self.labArea = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labArea.sizePolicy().hasHeightForWidth())
        self.labArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labArea.setFont(font)
        self.labArea.setObjectName("labArea")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labArea)
        self.doubleSpinBoxArea = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxArea.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxArea.setSizePolicy(sizePolicy)
        self.doubleSpinBoxArea.setMinimum(1.0)
        self.doubleSpinBoxArea.setMaximum(2.0)
        self.doubleSpinBoxArea.setSingleStep(0.01)
        self.doubleSpinBoxArea.setObjectName("doubleSpinBoxArea")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxArea)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxR = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxR.sizePolicy().hasHeightForWidth())
        self.spinBoxR.setSizePolicy(sizePolicy)
        self.spinBoxR.setMaximum(255)
        self.spinBoxR.setObjectName("spinBoxR")
        self.horizontalLayout.addWidget(self.spinBoxR)
        self.spinBoxG = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxG.sizePolicy().hasHeightForWidth())
        self.spinBoxG.setSizePolicy(sizePolicy)
        self.spinBoxG.setMaximum(255)
        self.spinBoxG.setObjectName("spinBoxG")
        self.horizontalLayout.addWidget(self.spinBoxG)
        self.spinBoxB = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxB.sizePolicy().hasHeightForWidth())
        self.spinBoxB.setSizePolicy(sizePolicy)
        self.spinBoxB.setMaximum(255)
        self.spinBoxB.setObjectName("spinBoxB")
        self.horizontalLayout.addWidget(self.spinBoxB)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBoxBgThresh = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxBgThresh.sizePolicy().hasHeightForWidth())
        self.spinBoxBgThresh.setSizePolicy(sizePolicy)
        self.spinBoxBgThresh.setMaximum(200000)
        self.spinBoxBgThresh.setObjectName("spinBoxBgThresh")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.spinBoxBgThresh)
        self.labTree = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labTree.sizePolicy().hasHeightForWidth())
        self.labTree.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labTree.setFont(font)
        self.labTree.setAlignment(QtCore.Qt.AlignCenter)
        self.labTree.setObjectName("labTree")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.labTree)
        self.spinBoxTree = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxTree.sizePolicy().hasHeightForWidth())
        self.spinBoxTree.setSizePolicy(sizePolicy)
        self.spinBoxTree.setMaximum(10)
        self.spinBoxTree.setObjectName("spinBoxTree")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.spinBoxTree)
        self.labChecks = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labChecks.sizePolicy().hasHeightForWidth())
        self.labChecks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labChecks.setFont(font)
        self.labChecks.setAlignment(QtCore.Qt.AlignCenter)
        self.labChecks.setObjectName("labChecks")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.labChecks)
        self.spinBoxChecks = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxChecks.sizePolicy().hasHeightForWidth())
        self.spinBoxChecks.setSizePolicy(sizePolicy)
        self.spinBoxChecks.setMaximum(100)
        self.spinBoxChecks.setObjectName("spinBoxChecks")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.spinBoxChecks)
        self.labRatio = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labRatio.sizePolicy().hasHeightForWidth())
        self.labRatio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labRatio.setFont(font)
        self.labRatio.setAlignment(QtCore.Qt.AlignCenter)
        self.labRatio.setOpenExternalLinks(False)
        self.labRatio.setObjectName("labRatio")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.labRatio)
        self.doubleSpinBoxRatio = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRatio.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRatio.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRatio.setMaximum(1.0)
        self.doubleSpinBoxRatio.setSingleStep(0.01)
        self.doubleSpinBoxRatio.setObjectName("doubleSpinBoxRatio")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxRatio)
        self.labK = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labK.sizePolicy().hasHeightForWidth())
        self.labK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labK.setFont(font)
        self.labK.setTextFormat(QtCore.Qt.AutoText)
        self.labK.setAlignment(QtCore.Qt.AlignCenter)
        self.labK.setObjectName("labK")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.labK)
        self.spinBoxK = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxK.sizePolicy().hasHeightForWidth())
        self.spinBoxK.setSizePolicy(sizePolicy)
        self.spinBoxK.setMaximum(10)
        self.spinBoxK.setObjectName("spinBoxK")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.spinBoxK)
        self.verticalLayout.addWidget(self.frame_2)
        self.btnSetDefault = QtWidgets.QPushButton(Dialog)
        self.btnSetDefault.setObjectName("btnSetDefault")
        self.verticalLayout.addWidget(self.btnSetDefault)
        self.btnDefault = QtWidgets.QPushButton(Dialog)
        self.btnDefault.setObjectName("btnDefault")
        self.verticalLayout.addWidget(self.btnDefault)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labExposureTime.setText(_translate("Dialog", "曝光时间(0-10000000μs)"))
        self.labTriggerDelay.setText(_translate("Dialog", "延迟时间(0-1000ms)"))
        self.label_2.setText(_translate("Dialog", "触发器触发间隔时间(s)"))
        self.label.setText(_translate("Dialog", "继电器输出时间(s)"))
        self.labMinMatchCount.setText(_translate("Dialog", "最小匹配数"))
        self.labResizeTime.setText(_translate("Dialog", "图片缩小倍数"))
        self.labMaxMatches.setText(_translate("Dialog", "最大特征点数"))
        self.labHist1.setText(_translate("Dialog", "颜色相似度(检测前)"))
        self.labHist2.setText(_translate("Dialog", "颜色相似度(检测后)"))
        self.labArea.setText(_translate("Dialog", "面积相似度"))
        self.label_3.setText(_translate("Dialog", "背景RGB值"))
        self.label_4.setText(_translate("Dialog", "背景的包容度"))
        self.labTree.setText(_translate("Dialog", "树的个数"))
        self.labChecks.setText(_translate("Dialog", "树遍历的次数"))
        self.labRatio.setText(_translate("Dialog", "特征点匹配比率"))
        self.labK.setText(_translate("Dialog", "k近邻搜索个数"))
        self.btnSetDefault.setText(_translate("Dialog", "设置默认值"))
        self.btnDefault.setText(_translate("Dialog", "恢复默认值"))


