# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogSelectTemp.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 900)
        Dialog.setMinimumSize(QtCore.QSize(1500, 900))
        Dialog.setMaximumSize(QtCore.QSize(1500, 900))
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grpAllTemp = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.grpAllTemp.setFont(font)
        self.grpAllTemp.setObjectName("grpAllTemp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpAllTemp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableViewAllTemp = QtWidgets.QTableView(self.grpAllTemp)
        self.tableViewAllTemp.setObjectName("tableViewAllTemp")
        self.verticalLayout_3.addWidget(self.tableViewAllTemp)
        self.frame_3 = QtWidgets.QFrame(self.grpAllTemp)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollAreaAllTemp = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollAreaAllTemp.setWidgetResizable(True)
        self.scrollAreaAllTemp.setObjectName("scrollAreaAllTemp")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labAllTemp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labAllTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labAllTemp.setObjectName("labAllTemp")
        self.verticalLayout_5.addWidget(self.labAllTemp)
        self.scrollAreaAllTemp.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollAreaAllTemp)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setObjectName("formLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSearch.sizePolicy().hasHeightForWidth())
        self.lineEditSearch.setSizePolicy(sizePolicy)
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEditSearch)
        self.btnSearch = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        self.btnSearch.setObjectName("btnSearch")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnSearch)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSave = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnRevert = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRevert.sizePolicy().hasHeightForWidth())
        self.btnRevert.setSizePolicy(sizePolicy)
        self.btnRevert.setObjectName("btnRevert")
        self.horizontalLayout_4.addWidget(self.btnRevert)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frame_7)
        self.btnDelete = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setObjectName("btnDelete")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btnDelete)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(0, 6)
        self.verticalLayout_3.setStretch(1, 4)
        self.horizontalLayout.addWidget(self.grpAllTemp)
        self.grpSelectTemp = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.grpSelectTemp.setFont(font)
        self.grpSelectTemp.setObjectName("grpSelectTemp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grpSelectTemp)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidgetSelectTemp = QtWidgets.QTableWidget(self.grpSelectTemp)
        self.tableWidgetSelectTemp.setObjectName("tableWidgetSelectTemp")
        self.tableWidgetSelectTemp.setColumnCount(0)
        self.tableWidgetSelectTemp.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidgetSelectTemp)
        self.frame_5 = QtWidgets.QFrame(self.grpSelectTemp)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBoxIgnoreColor = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxIgnoreColor.sizePolicy().hasHeightForWidth())
        self.checkBoxIgnoreColor.setSizePolicy(sizePolicy)
        self.checkBoxIgnoreColor.setObjectName("checkBoxIgnoreColor")
        self.verticalLayout_9.addWidget(self.checkBoxIgnoreColor)
        self.btnSelect = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelect.sizePolicy().hasHeightForWidth())
        self.btnSelect.setSizePolicy(sizePolicy)
        self.btnSelect.setObjectName("btnSelect")
        self.verticalLayout_9.addWidget(self.btnSelect)
        self.btnRemove = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemove.sizePolicy().hasHeightForWidth())
        self.btnRemove.setSizePolicy(sizePolicy)
        self.btnRemove.setObjectName("btnRemove")
        self.verticalLayout_9.addWidget(self.btnRemove)
        self.btnClear = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout_9.addWidget(self.btnClear)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollAreaSelectTemp = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollAreaSelectTemp.setWidgetResizable(True)
        self.scrollAreaSelectTemp.setObjectName("scrollAreaSelectTemp")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 237))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labSelectTemp = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labSelectTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labSelectTemp.setObjectName("labSelectTemp")
        self.verticalLayout_8.addWidget(self.labSelectTemp)
        self.scrollAreaSelectTemp.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollAreaSelectTemp)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_6.setStretch(0, 6)
        self.verticalLayout_6.setStretch(1, 4)
        self.horizontalLayout.addWidget(self.grpSelectTemp)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.grpAllTemp.setTitle(_translate("Dialog", "所有模板"))
        self.groupBox_3.setTitle(_translate("Dialog", "模板图片"))
        self.labAllTemp.setText(_translate("Dialog", "无"))
        self.btnSearch.setText(_translate("Dialog", "过滤"))
        self.btnSave.setText(_translate("Dialog", "保存"))
        self.btnRevert.setText(_translate("Dialog", "取消修改"))
        self.btnDelete.setText(_translate("Dialog", "删除"))
        self.grpSelectTemp.setTitle(_translate("Dialog", "已选择的模板"))
        self.checkBoxIgnoreColor.setText(_translate("Dialog", "检测时同型号同大小忽略颜色"))
        self.btnSelect.setText(_translate("Dialog", "选择模板"))
        self.btnRemove.setText(_translate("Dialog", "移除所选模板"))
        self.btnClear.setText(_translate("Dialog", "清空所有已选模板"))
        self.groupBox_4.setTitle(_translate("Dialog", "模板图片"))
        self.labSelectTemp.setText(_translate("Dialog", "无"))


