# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(880, 571)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grpCamera = QtWidgets.QGroupBox(self.frame_3)
        self.grpCamera.setObjectName("grpCamera")
        self.gridLayout = QtWidgets.QGridLayout(self.grpCamera)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.labDetectCamera = QtWidgets.QLabel(self.grpCamera)
        self.labDetectCamera.setObjectName("labDetectCamera")
        self.gridLayout.addWidget(self.labDetectCamera, 0, 1, 1, 1)
        self.labLinkCamera = QtWidgets.QLabel(self.grpCamera)
        self.labLinkCamera.setObjectName("labLinkCamera")
        self.gridLayout.addWidget(self.labLinkCamera, 2, 1, 1, 1)
        self.btnLinkCamera = QtWidgets.QPushButton(self.grpCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLinkCamera.sizePolicy().hasHeightForWidth())
        self.btnLinkCamera.setSizePolicy(sizePolicy)
        self.btnLinkCamera.setObjectName("btnLinkCamera")
        self.gridLayout.addWidget(self.btnLinkCamera, 2, 0, 1, 1)
        self.btnDetectCamera = QtWidgets.QPushButton(self.grpCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDetectCamera.sizePolicy().hasHeightForWidth())
        self.btnDetectCamera.setSizePolicy(sizePolicy)
        self.btnDetectCamera.setObjectName("btnDetectCamera")
        self.gridLayout.addWidget(self.btnDetectCamera, 0, 0, 1, 1)
        self.btnTestCamera = QtWidgets.QPushButton(self.grpCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTestCamera.sizePolicy().hasHeightForWidth())
        self.btnTestCamera.setSizePolicy(sizePolicy)
        self.btnTestCamera.setObjectName("btnTestCamera")
        self.gridLayout.addWidget(self.btnTestCamera, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.grpCamera)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.btnCloseCamera = QtWidgets.QPushButton(self.grpCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloseCamera.sizePolicy().hasHeightForWidth())
        self.btnCloseCamera.setSizePolicy(sizePolicy)
        self.btnCloseCamera.setObjectName("btnCloseCamera")
        self.gridLayout.addWidget(self.btnCloseCamera, 5, 0, 1, 1)
        self.labCloseCamera = QtWidgets.QLabel(self.grpCamera)
        self.labCloseCamera.setObjectName("labCloseCamera")
        self.gridLayout.addWidget(self.labCloseCamera, 5, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 4)
        self.verticalLayout_3.addWidget(self.grpCamera)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grpDetect = QtWidgets.QGroupBox(self.frame)
        self.grpDetect.setObjectName("grpDetect")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grpDetect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStartDetect = QtWidgets.QPushButton(self.grpDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartDetect.sizePolicy().hasHeightForWidth())
        self.btnStartDetect.setSizePolicy(sizePolicy)
        self.btnStartDetect.setObjectName("btnStartDetect")
        self.verticalLayout.addWidget(self.btnStartDetect)
        self.btnStopDetect = QtWidgets.QPushButton(self.grpDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStopDetect.sizePolicy().hasHeightForWidth())
        self.btnStopDetect.setSizePolicy(sizePolicy)
        self.btnStopDetect.setObjectName("btnStopDetect")
        self.verticalLayout.addWidget(self.btnStopDetect)
        self.btnSetParams = QtWidgets.QPushButton(self.grpDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetParams.sizePolicy().hasHeightForWidth())
        self.btnSetParams.setSizePolicy(sizePolicy)
        self.btnSetParams.setObjectName("btnSetParams")
        self.verticalLayout.addWidget(self.btnSetParams)
        self.horizontalLayout_2.addWidget(self.grpDetect)
        self.grpTemp = QtWidgets.QGroupBox(self.frame)
        self.grpTemp.setObjectName("grpTemp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpTemp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSelectTemp = QtWidgets.QPushButton(self.grpTemp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectTemp.sizePolicy().hasHeightForWidth())
        self.btnSelectTemp.setSizePolicy(sizePolicy)
        self.btnSelectTemp.setObjectName("btnSelectTemp")
        self.verticalLayout_2.addWidget(self.btnSelectTemp)
        self.btnMakeTemp = QtWidgets.QPushButton(self.grpTemp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMakeTemp.sizePolicy().hasHeightForWidth())
        self.btnMakeTemp.setSizePolicy(sizePolicy)
        self.btnMakeTemp.setObjectName("btnMakeTemp")
        self.verticalLayout_2.addWidget(self.btnMakeTemp)
        self.horizontalLayout_2.addWidget(self.grpTemp)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.grpInput = QtWidgets.QGroupBox(self.frame_2)
        self.grpInput.setObjectName("grpInput")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grpInput)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labInput = QtWidgets.QLabel(self.grpInput)
        self.labInput.setObjectName("labInput")
        self.verticalLayout_4.addWidget(self.labInput)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addWidget(self.grpInput)
        self.grpOuput = QtWidgets.QGroupBox(self.frame_2)
        self.grpOuput.setObjectName("grpOuput")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grpOuput)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labOutput = QtWidgets.QLabel(self.grpOuput)
        self.labOutput.setObjectName("labOutput")
        self.verticalLayout_5.addWidget(self.labOutput)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addWidget(self.grpOuput)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grpCamera.setTitle(_translate("Form", "相机"))
        self.labDetectCamera.setText(_translate("Form", "无"))
        self.labLinkCamera.setText(_translate("Form", "未连接"))
        self.btnLinkCamera.setText(_translate("Form", "连接相机"))
        self.btnDetectCamera.setText(_translate("Form", "检测相机"))
        self.btnTestCamera.setText(_translate("Form", "测试相机"))
        self.label.setText(_translate("Form", "未开始测试"))
        self.btnCloseCamera.setText(_translate("Form", "关闭相机"))
        self.labCloseCamera.setText(_translate("Form", "无"))
        self.grpDetect.setTitle(_translate("Form", "检测"))
        self.btnStartDetect.setText(_translate("Form", "开始检测"))
        self.btnStopDetect.setText(_translate("Form", "停止检测"))
        self.btnSetParams.setText(_translate("Form", "设置参数"))
        self.grpTemp.setTitle(_translate("Form", "模板"))
        self.btnSelectTemp.setText(_translate("Form", "选择模板"))
        self.btnMakeTemp.setText(_translate("Form", "拍摄模板"))
        self.grpInput.setTitle(_translate("Form", "输入图片"))
        self.labInput.setText(_translate("Form", "无图片"))
        self.grpOuput.setTitle(_translate("Form", "匹配结果"))
        self.labOutput.setText(_translate("Form", "无结果"))


